# Generated by Django 3.2.16 on 2022-11-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
                'db_table': 'stadiums',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=16)),
                ('seat_num', models.IntegerField()),
                ('stadium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seat',
                'db_table': 'seat',
            },
        ),
    ]
