# Generated by Django 3.2.16 on 2022-11-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='stadium_id',
            new_name='stadium',
        ),
    ]
