# Generated by Django 3.2.16 on 2022-11-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_rename_stadium_id_seat_stadium'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadium',
            unique_together={('name', 'city')},
        ),
    ]
