# Generated by Django 3.2.16 on 2022-11-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('members_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('match_time', models.DateTimeField()),
                ('match_duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesting_matches', to='matches.team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_matches', to='matches.team')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'match',
            },
        ),
    ]
