# Generated by Django 3.2.16 on 2022-11-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='is_active',
            new_name='is_selling_ticket_active',
        ),
    ]
