# Generated by Django 3.2.16 on 2022-11-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_alter_stadium_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0003_alter_match_match_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'seat_match',
                'verbose_name_plural': 'seat_matches',
                'db_table': 'seat_match',
            },
        ),
    ]
