# Generated by Django 3.2.16 on 2022-11-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20221103_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchseat',
            options={'verbose_name': 'Match Seat', 'verbose_name_plural': 'Match Seats'},
        ),
        migrations.RemoveField(
            model_name='matchseat',
            name='user',
        ),
    ]
